### ISSUE TITLE
Pattern program

### ISSUE THREAD

**Issue by Moumita-08** [Moumita-08/Hacktoberfest#12]
Print the following pattern

* * * * * * * * * * * * * * * * * * * * * * * * *
  *           *   *           *   *           *
    *       *       *       *       *       *
      *   *           *   *           *   *
        *               *               *
      *   *           *   *           *   *
    *       *       *       *       *       *
  *           *   *           *   *           *
* * * * * * * * * * * * * * * * * * * * * * * * *

**Comment by kashish0604** [comment]
hey  @Moumita-08 can you assign this issue to me i can work on it

**Comment by Moumita-08** [comment]
ok go ahead
@kashish0604
