### ISSUE TITLE
Check Sparse Matrix or Not

### ISSUE THREAD

**Issue by Moumita-08** [Moumita-08/Hacktoberfest#18]
Input a matrix of size (m x n) and check whether it is a **sparse matrix** or not. A sparse matrix is a matrix where the number of zero elements is greater than the number of non-zero elements.

**Comment by sayan901** [comment]
Can you assign me ?

**Comment by Moumita-08** [comment]
okay @sayan901 , go ahead

**Comment by goyalsaksh** [comment]
@Moumita-08 please assign it to me

**Comment by avishagoyal08** [comment]
Please assign it to me. I will try my best to solve it in an effective way.

**Comment by mehakbasrani** [comment]
can you assign it to me?
